### ISSUE TITLE
webinspect kicking off 2 scans 

### ISSUE THREAD

**Issue by matt-fevold** [target/webbreaker#121]
Below are required fields for qualifying your issue to our support team.

### Subject of the issue
- [x] Briefly describe your issue. More details can be added below.
Recently discovered that webinspect is kicking off 2 scans and causing errors. 

You have to wait for both scans to complete before getting feedback and if either fail you get no scan downloaded/incomplete scan

Compiling with PyInstaller produces this error 100% of the time
Source compilation has this issue some % of the time.

### Your environment
- [ ] Verify you are using the most recent version of WebBreaker
- [ ] Python version
- [ ] Operating System
- [ ] WebInspect, Fortify SSC, ThreadFix versions (if relevant)

### Relevant WebBreaker commands
- [ ] List all relevant WebBreaker commands.
- [ ] Verify you have redacted any sensitive hostnames, credentials, application names, etc from these commands

### Expected behaviour
- [ ] Tell us what should happen

### Actual behaviour
- [ ] Tell us what happens instead, including any relevant errors or stacktraces
- [ ] Verify you have redacted any sensitive hostnames, credentials, application names, etc from these errors/ stacktraces

**Comment by matt-fevold** [comment]
I checked out the flow of WebInspectClient and don't believe the problem is there. Keeping on looking.

**Comment by xolian** [comment]
Remediated by removing extra webbreaker.webinspectclient response variable
