### ISSUE TITLE
Fix comments in confighelper.py

### ISSUE THREAD

**Issue by matt-fevold** [target/webbreaker#123]
Below are required fields for qualifying your issue to our support team.

### Subject of the issue
- [ ] Briefly describe your issue. More details can be added below.
In the confighelper.py there is the issue where if the config.ini already exists the comments become unreadable (everything is out of order)

### Your environment
- [ ] Verify you are using the most recent version of WebBreaker
- [ ] Python version
- [ ] Operating System
- [ ] WebInspect, Fortify SSC, ThreadFix versions (if relevant)

### Relevant WebBreaker commands
- [ ] List all relevant WebBreaker commands.
- [ ] Verify you have redacted any sensitive hostnames, credentials, application names, etc from these commands

### Expected behaviour
- [ ] Tell us what should happen

### Actual behaviour
- [ ] Tell us what happens instead, including any relevant errors or stacktraces
- [ ] Verify you have redacted any sensitive hostnames, credentials, application names, etc from these errors/ stacktraces

**Comment by matt-fevold** [comment]
This issue was created from PR #122

**Comment by xolian** [comment]
removed comments in config.ini, roadmap is to move towards a json structure from ini
