### ISSUE TITLE
SSC URL Fix

### ISSUE THREAD

**Issue by mfeferman** [target/webbreaker#147]
Below are required fields for qualifying your issue to our support team.

### Subject of the issue
Using a non-standard URL for SSC, anything other than .../ssc breaks webbreaker.  I should be able to specify my full URI to the SSC instance in the config.ini file.  E.g., http://<server>:8180/ssc1720

### Your environment
Webbreaker 2.1.7
Python v2.7.12
Ubuntu 16.04
WebInspect v17.10, SSC v17.20

### Relevant WebBreaker commands
webbreaker fortify list

### Expected behaviour
I would expect it to list my apps/versions in ssc

### Actual behaviour
An error was thrown.  I see that I was including my non-standard SSC URL, so I need to exclude it.  

However, the full SSC URL needs to be configurable.

**Comment by xolian** [comment]
This issue will require `uri` and `url` values to be modified under the pypi module https://github.com/target/fortifyapi.  Consequently, a new branch has been created for the remediation, hotfix-fortify-context-url

**Comment by xolian** [comment]
Fixed in latest version 2.1.10
