### ISSUE TITLE
JSON could not be decoded - threadfix applications

### ISSUE THREAD

**Issue by matt-fevold** [target/webbreaker#159]
When running the following command I got this JSON could not be decoded error.
I got the same issue on different --team_id's also running this on master branch. 
We haven't tested this in awhile so no idea if/when it was last working.

➜ webbreaker threadfix applications --team_id 123

Version 2.1.13
Logging to files: /Users/REDACTED/.webbreaker/log/webbreaker-04-19-2018.log
JSON response could not be decoded.
Threadfix exited
123
No applications were found for team_id 123

**Comment by xolian** [comment]
remediated in https://github.com/target/webbreaker/pull/180
