### ISSUE TITLE
Webbreaker webinspect download not working

### ISSUE THREAD

**Issue by matt-fevold** [target/webbreaker#165]
Below are required fields for qualifying your issue to our support team.

### Subject of the issue
- [ ] Briefly describe your issue. More details can be added below.
 webbreaker webinspect download --server SERVERNAME --scan_name SCANNAME --scan_id SCANID

produces the following stacktrace:
File "/Users/redacted/pse/webbreaker/venv36/lib/python3.6/site-packages/webbreaker-2.1.20.dev0-py3.6.egg/webbreaker/webinspect/common/helper.py", line 119, in export_scan_results
AttributeError: 'WebInspectAPIHelper' object has no attribute 'setting_overrides'

### Your environment
- [ ] Verify you are using the most recent version of WebBreaker
using a dev environment - almost certainly can reproduce on 2.1.19 
- [ ] Python version
3.6

This is something that I found while developing something else for webbreaker and will circle back around to fix at a later date.

**Comment by xolian** [comment]
remediated with #168 PR.
