### ISSUE TITLE
JSON generated with WebInspect Scan could not be parsed

### ISSUE THREAD

**Issue by rsmartins78** [target/webbreaker#179]
### Subject of the issue
- JSON generated with WebInspect Scan could not be parsed

### Your environment
- [Yes] Verify you are using the most recent version of WebBreaker
- [Docker] Python version
- [Docker] Operating System
- [Latest Trial] WebInspect, Fortify SSC, ThreadFix versions (if relevant)

### Expected behaviour
- Generate a valid JSON with brackets making the findings field an array.

### Actual behaviour
- The "findings" field of the json file is an array, but its writing does not have a "[]" bracket.
Error encountered in JSONLint.
When manually correcting by inserting a bracket "[" and "]" at the end of the code, JSON is valid and can be parsed. 

Sorry for my english.

**Comment by xolian** [comment]
Thanks for opening up the issue Rafael and PR, if I may ask what is your use case for parsing?  Are you forwarding the <webinspect>.json to an ELK, Splunk, or other?  Curious on your use-case.

**Comment by rsmartins78** [comment]
I have an application with a pipeline in Gitlab-CI. One of the jobs in this pipeline is the WebInspect vulnerability test through the Webbreaker in container. And the following Job is a container with a shell script that I wrote that parses JSON and kills the pipeline when it encounters vulnerability with a certain severity level.

**Comment by rsmartins78** [comment]
Thank you.
