### ISSUE TITLE
WIE - WebInspect Enterprise REST API Compability

### ISSUE THREAD

**Issue by rsmartins78** [target/webbreaker#182]
This issue is more of a question than a issue in fact.
I'm currently with a project in a large Brazilian bank that needs to integrate WebInspect Enterprise with Jenkins Pipelines. I used the webbreaker in the past, I even pulled a pull request to this repository to fix a small problem, but now I'd like to know if the webbreaker is compatible with the WebInspect Enterprise REST API, since API endpoints change between versions Standalone and Enterprise.

**Comment by AUAlumMN** [comment]
Hi!  We are currently evaluating future state of WebBreaker and will have an update soon.

**Comment by rsmartins78** [comment]
Ok, Thanks.
