### ISSUE TITLE
Setup.py Cryptography PYPI Module Does not Properly Install

### ISSUE THREAD

**Issue by xolian** [target/webbreaker#21]
Setup fails on cryptography module.  The use case, is on initial install of executing `python setup.py install` is an error thrown of failing to install the [cryptography pypi module](https://pypi.python.org/pypi/cryptography).  User is required to perform a `pip install cryptography` prior to running `python setup.py install`.

**Comment by mdunaj** [comment]
Fixed in PR #24 . Solution was moving cryptography to requirements.txt and adding an extra step to the install process.
