### ISSUE TITLE
Remove help text prior to execution

### ISSUE THREAD

**Issue by djvillafana** [target/webbreaker#30]
It is possible I'm doing something wrong, but all the help text for webbreaker is printed to the console prior to the program execution. It should only do this when command is missing required arguments and execution is not possible.

**Comment by xolian** [comment]
execution of simply `webbreaker` without an upper level command, such as `fortify` or `webinspect` provides all the upper and lower level commands with their respective options, this is expected behavior.

**Comment by mdunaj** [comment]
Fixed in PR #32

**Comment by xolian** [comment]
remediated by creating `help_description`, reformatting help text available in dev branch
