### ISSUE TITLE
Treatment of both git_url and server options 

### ISSUE THREAD

**Issue by xolian** [target/webbreaker#47]
Both git_url and the server options may be non-intuitive for users, the following enhancements should be made and accepted as valid argv's.
- [x] The `webbreaker admin notifier --git_url` option requires an https rather than a git url.  Either a condition or exception should be provided if a git url or non-https is provided as argv.
- [x] The `str.strip` should be implemented,  if https / http is provided as a command-line argv, such as `webbreaker webinspect list --server https://webinspect-1.example.com:8083`.  The new `str.strip` implementation should remove the `https://`.

**Comment by mdunaj** [comment]
Fixed in #49
