### ISSUE TITLE
Review unneeded variables 

### ISSUE THREAD

**Issue by KylerWitting** [target/webbreaker#50]
- __main__.py issues 
  - @pass_config in main is not currently used
  - import os not used 
  - SecretClient is not used 
- handle_scan_event = None & reporter = None 
  - Both variables are set in __main__.py & webinspectorscanhelpers.py

**Comment by matt-fevold** [comment]
- more __main__.py issues
  - servers_list(config) (line 352) has no usages

**Comment by matt-fevold** [comment]
- webinspectconfig.py
  -  Class WebInspectEndpoint has no usage
