### ISSUE TITLE
Webbreaker Webinspect Proxy Settings Download

### ISSUE THREAD

**Issue by xolian** [target/webbreaker#85]
The command `webbreaker webinspect proxy --stop --scan_name=abc-123`
Downloads only a webmacro for both the .webmacro and .xml file types.  Below illustrates a successful test implementing the Webinspect proxy endpoint for downloading a webmacro encapsulated within a settings file as a .xml format.

curl -X GET --header 'Accept: application/octet-stream' 'https://webinspect1.example.com:8083/webinspect/proxy/abc-123.xml' > abc-123-proxy-settings.xml

**Comment by mdunaj** [comment]
Fixed in #87
