### ISSUE TITLE
webbreaker_install and webinspect_repo fail when launching a scan

### ISSUE THREAD

**Issue by xolian** [target/webbreaker#89]
A webinspect scan fails, when launching a `webbreaker webinspect scan --settings myscan.xml`.  The `dir` settings are not consistent, one `--settings` option will identify a settings file in a different location than where my git repo exists as determined by the other `dir` value.

**Comment by xolian** [comment]
Remove the two directory settings in the config.ini, values will no longer be configurable by the user, rather directory structures will be tightly coupled to the user home directory under the ($HOME or %USERPROFILE%) .webbreaker subdirectory.  Configuration values affected and scoped for the change are.

```
[webbreaker_install]
dir = .

[webinspect_repo]
dir = ./.webbreaker/etc/webinspect
```

**Comment by xolian** [comment]
Refactor config.ini blocks for `webinspect`, `threadfix`, and `fortify`, values.  Current blocks in-scope for refactoring are listed below.

```
<insert blocks here
```

**Comment by KylerWitting** [comment]
PR #93 partially corrected the issue. There is still a couple of corrections to be made in webinspect config to resolve bug

**Comment by xolian** [comment]
remediated in v2.0.06 dir_static branch
